/**
 * Codix Wellness — Product & Content Data
 * All data arrays used by the site are centralized here.
 */

const PRODUCTS = {
  all: [
    {
      id: "p1",
      name: "Codixvitamin D3 Oral Solution",
      category: "Supplements",
      label: "New",
      price: "$18.00 - $35.00",
      reviews: 85,
      rating: 5,
      image: "images/product-vitamin-cd.jpg",
    },
    {
      id: "p2",
      name: "YOUR GUMMIE Collagen Plus +",
      category: "Supplements",
      label: "Sale",
      price: "$16.00 - $25.00",
      reviews: 103,
      rating: 5,
      image: "images/product-gummie.jpg",
    },
    {
      id: "p3",
      name: "Boloss Liver Support Complex",
      category: "Medicines",
      label: "Sale",
      price: "$19.00 - $28.00",
      reviews: 78,
      rating: 5,
      image: "images/product-capsules.jpg",
    },
    {
      id: "p4",
      name: "Essence – Evening Primrose Oil",
      category: "Herbs",
      label: "New",
      price: "$16.00 - $22.00",
      reviews: 47,
      rating: 5,
      image: "images/product-purple.jpg",
    },
    {
      id: "p5",
      name: "Your Gummy – Milk Multi Gummies",
      category: "Supplements",
      label: "Sale",
      price: "$20.00 - $32.00",
      reviews: 168,
      rating: 5,
      image: "images/product-gummie.jpg",
    },
    {
      id: "p6",
      name: "Relax Herbal Blend",
      category: "Herbs",
      label: "New",
      price: "$16.00 - $20.00",
      reviews: 42,
      rating: 5,
      image: "images/product-capsules.jpg",
    },
    {
      id: "p7",
      name: "Joint Relief Boost",
      category: "Medicines",
      label: "Sale",
      price: "$22.00 - $30.00",
      reviews: 111,
      rating: 5,
      image: "images/product-red.jpg",
    },
  ],

  featured: [
    {
      id: "f1",
      name: "Codixvitamin D3 Oral Solution",
      label: "New",
      price: "$18.00 - $35.00",
      reviews: 85,
      rating: 5,
      image: "images/product-vitamin-cd.jpg",
      category: "Supplements",
    },
    {
      id: "f2",
      name: "Your Gummy – Multi Gummies",
      label: "Sale",
      price: "$16.00 - $25.00",
      reviews: 103,
      rating: 5,
      image: "images/product-gummie.jpg",
      category: "Supplements",
    },
    {
      id: "f3",
      name: "Magnesium Glycinate",
      label: "New",
      price: "$19.00 - $29.00",
      reviews: 90,
      rating: 5,
      image: "images/product-capsules.jpg",
      category: "Supplements",
    },
    {
      id: "f4",
      name: "Tart Cherry – Apple Cider Vinegar",
      label: "Sale",
      price: "$21.00 - $31.00",
      reviews: 68,
      rating: 5,
      image: "images/product-red.jpg",
      category: "Herbs",
    },
    {
      id: "f5",
      name: "Flexicod – Joint Health Support",
      label: "New",
      price: "$18.00 - $26.00",
      reviews: 114,
      rating: 5,
      image: "images/product-gummie.jpg",
      category: "Medicines",
    },
    {
      id: "f6",
      name: "Daily Balance – Multivitamin",
      label: "Sale",
      price: "$17.00 - $24.00",
      reviews: 56,
      rating: 5,
      image: "images/product-purple.jpg",
      category: "Supplements",
    },
    {
      id: "f7",
      name: "Supplements, Beauty & Skin Health",
      label: "New",
      price: "$15.00 - $23.00",
      reviews: 72,
      rating: 5,
      image: "images/product-vitamin-cd.jpg",
      category: "Supplements",
    },
    {
      id: "f8",
      name: "Supplements, Immune Support",
      label: "Sale",
      price: "$14.00 - $22.00",
      reviews: 88,
      rating: 5,
      image: "images/product-capsules.jpg",
      category: "Supplements",
    },
    {
      id: "f9",
      name: "Supplements, Energy & Vitality",
      label: "New",
      price: "$18.00 - $28.00",
      reviews: 65,
      rating: 5,
      image: "images/product-red.jpg",
      category: "Supplements",
    },
    {
      id: "f10",
      name: "Codix Multi Plus",
      label: "Sale",
      price: "$16.00 - $25.00",
      reviews: 94,
      rating: 5,
      image: "images/product-gummie.jpg",
      category: "Medicines",
    },
    {
      id: "f11",
      name: "Day 3 Day Collagen Mix Plus",
      label: "New",
      price: "$24.00 - $32.00",
      reviews: 52,
      rating: 5,
      image: "images/product-purple.jpg",
      category: "Supplements",
    },
    {
      id: "f12",
      name: "Herb Harmony – Herbal & Ama…",
      label: "Sale",
      price: "$13.00 - $19.00",
      reviews: 77,
      rating: 5,
      image: "images/product-capsules.jpg",
      category: "Herbs",
    },
    {
      id: "f13",
      name: "Your Green – Fish & Nail…",
      label: "New",
      price: "$20.00 - $30.00",
      reviews: 61,
      rating: 5,
      image: "images/product-vitamin-cd.jpg",
      category: "Supplements",
    },
    {
      id: "f14",
      name: "Tart Cherry – Apple Cider Vinegar",
      label: "Sale",
      price: "$15.00 - $22.00",
      reviews: 83,
      rating: 5,
      image: "images/product-red.jpg",
      category: "Herbs",
    },
    {
      id: "f15",
      name: "Supplements, Cognitive Health",
      label: "New",
      price: "$17.00 - $26.00",
      reviews: 44,
      rating: 5,
      image: "images/product-gummie.jpg",
      category: "Supplements",
    },
  ],

  bestSelling: [
    {
      id: "b1",
      name: "Codixvitamin D3 Oral Solution",
      label: "New",
      price: "$18.00 - $35.00",
      reviews: 85,
      rating: 5,
      image: "images/product-vitamin-cd.jpg",
      category: "Supplements",
    },
    {
      id: "b2",
      name: "YOUR GUMMIE Collagen Plus +",
      label: "Sale",
      price: "$16.00 - $25.00",
      reviews: 103,
      rating: 5,
      image: "images/product-gummie.jpg",
      category: "Supplements",
    },
    {
      id: "b3",
      name: "Boloss Liver Support Complex",
      label: "Sale",
      price: "$19.00 - $28.00",
      reviews: 78,
      rating: 5,
      image: "images/product-capsules.jpg",
      category: "Medicines",
    },
    {
      id: "b4",
      name: "Essence – Evening Primrose Oil",
      label: "New",
      price: "$16.00 - $22.00",
      reviews: 47,
      rating: 5,
      image: "images/product-purple.jpg",
      category: "Herbs",
    },
    {
      id: "b5",
      name: "Your Gummy – Milk Multi Gummies",
      label: "Sale",
      price: "$20.00 - $32.00",
      reviews: 168,
      rating: 5,
      image: "images/product-gummie.jpg",
      category: "Supplements",
    },
  ],

  categories: ["Supplements", "Medicines", "Herbs"],
};

const HERO_SLIDES = [
  {
    title: "YOUR GUMMIE",
    titleHighlight: "FOR MEN",
    subtitle: "Support Your Strength, Every Day",
    button: "Buy it now",
    bgImage: "images/hero-bg.png",
  },
  {
    title: "CODIX EVEROSE",
    titleHighlight: "DAILY CARE",
    subtitle: "Balanced Daily Vitamins Crafted For Modern Wellness",
    button: "Shop Everose",
    bgImage: "images/hero-bg.png",
  },
  {
    title: "FLEXICOD",
    titleHighlight: "JOINT SUPPORT",
    subtitle: "Advanced Mobility Support With Premium Botanical Extracts",
    button: "Shop Flexicod",
    bgImage: "images/hero-bg.png",
  },
];

const TESTIMONIALS = [
  {
    quote:
      "But I have been using for about 18 Mo contain a lot of researching relevant and effective for the body.",
    name: "Tina Lee",
    rating: 5,
  },
  {
    quote:
      "There was a small problem in the order, the service got this center under and I could live really good. The delivery was fast enough.",
    name: "Michael Shaw",
    rating: 5,
  },
  {
    quote:
      "Those selling this DO provide quality changes but only brand I use. I use changes to space of months by buying from them.",
    name: "Aisha Roberts",
    rating: 5,
  },
];

const BLOG_POSTS = [
  {
    title: "5 Natural Ways to Strengthen Your Immune System",
    description:
      "Discover simple lifestyle habits and key supplements that can naturally boost your immunity...",
    image: "images/blog-immune.jpg",
    tag: "Wellness Guide",
  },
  {
    title: "Skincare Advice for Sensitive Skin: Simple Tips for a Calmer Glow",
    description:
      "Learn how to care for sensitive skin with gentle routines and dermatologist recommended products.",
    image: "images/blog-immune.jpg",
    tag: "Beauty & Skin",
  },
  {
    title: "Do You Really Need Supplements? A Practical Guide to Boosting Health",
    description:
      "Find out when supplements are helpful and how to choose the right ones for your health needs.",
    image: "images/blog-immune.jpg",
    tag: "Health Guide",
  },
];

const TRUST_ITEMS = [
  { icon: "fa-money-bill-wave", label: "100% Money back", description: "Satisfaction guaranteed." },
  { icon: "fa-shipping-fast", label: "Non-contact shipping", description: "Safe delivery." },
  { icon: "fa-truck", label: "Free delivery over $200", description: "On higher orders." },
];

const SAMPLE_SEARCH_PRODUCTS = [
  "Codix Vitamin C+D",
  "Your Gummie Fish Oil",
  "ReliefMax Capsules",
  "Herbal Immune Support",
  "Daily Focus Gummies",
  "Relax Herbal Blend",
  "Joint Relief Boost",
  "Codix Everose",
  "Flexicod",
  "Codix Fatburner",
  "Daily Balance",
];
