/**
 * Codix Wellness — Product & Content Data
 * All data arrays used by the site are centralized here.
 */

const PRODUCTS = {
  all: [
    {
      id: "p1",
      name: "Codferol Vitamin D3 Oral Solution",
      category: "Supplements, Vitamins",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 1,
      rating: 5,
      image: "images/f-grid-1.png",
    },
    {
      id: "p2",
      name: "Your Gummie – Kids Multi Gummie",
      category: "Supplements, Kids Vitamins",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 103,
      rating: 5,
      image: "images/f-grid-2.png",
    },
    {
      id: "p3",
      name: "Your Gummie Apple Cider Vinegar",
      category: "Supplements, Weight Management",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 143,
      rating: 5,
      image: "images/f-grid-3.png",
    },
    {
      id: "p4",
      name: "Flexicod – Joint Health Support",
      category: "Supplements, Joint Support",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 102,
      rating: 5,
      image: "images/f-grid-4.png",
    },
    {
      id: "p5",
      name: "Codix Fatburner – Metabolism Support",
      category: "Supplements, Weight Management",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 97,
      rating: 5,
      image: "images/f-grid-5.png",
    },
    {
      id: "p6",
      name: "Day 2 Day Collagen Mag Plus",
      category: "Supplements, Beauty & Skin Health",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 76,
      rating: 5,
      image: "images/f-grid-6.png",
    },
    {
      id: "p7",
      name: "Your Gummie – Defence Vitamin C & Zinc",
      category: "Supplements, Immune Support",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 134,
      rating: 5,
      image: "images/f-grid-7.png",
    },
  ],

  featured: [
    {
      id: "f1",
      name: "Codferol Vitamin D3 Oral Solution",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 1,
      rating: 5,
      image: "images/f-grid-1.png",
      category: "Supplements, Vitamins",
    },
    {
      id: "f2",
      name: "Your Gummie – Kids Multi Gummie",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 103,
      rating: 5,
      image: "images/f-grid-2.png",
      category: "Supplements, Kids Vitamins",
    },
    {
      id: "f3",
      name: "Your Gummie Apple Cider Vinegar",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 143,
      rating: 5,
      image: "images/f-grid-3.png",
      category: "Supplements, Weight Management",
    },
    {
      id: "f4",
      name: "Flexicod – Joint Health Support",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 102,
      rating: 5,
      image: "images/f-grid-4.png",
      category: "Supplements, Joint Support",
    },
    {
      id: "f5",
      name: "Codix Fatburner – Metabolism Support",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 97,
      rating: 5,
      image: "images/f-grid-5.png",
      category: "Supplements, Weight Management",
    },
    {
      id: "f6",
      name: "Day 2 Day Collagen Mag Plus",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 76,
      rating: 5,
      image: "images/f-grid-6.png",
      category: "Supplements, Beauty & Skin Health",
    },
    {
      id: "f7",
      name: "Your Gummie – Defence Vitamin C & Zinc",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 134,
      rating: 5,
      image: "images/f-grid-7.png",
      category: "Supplements, Immune Support",
    },
    {
      id: "f8",
      name: "Codix Maca Root",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 89,
      rating: 5,
      image: "images/f-grid-8.png",
      category: "Supplements, Energy & Vitality",
    },
    {
      id: "f9",
      name: "Your Gummie – 5-HTP Complex",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 112,
      rating: 5,
      image: "images/f-grid-9.png",
      category: "Supplements, Immune Support",
    },
    {
      id: "f10",
      name: "Your Gummie – Men's Multi",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 95,
      rating: 5,
      image: "images/f-grid-10.png",
      category: "Supplements, Men's Health",
    },
    {
      id: "f11",
      name: "Your Gummie – Women's Multi",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 132,
      rating: 5,
      image: "images/f-grid-11.png",
      category: "Supplements, Women's Health",
    },
    {
      id: "f12",
      name: "Your Gummie – Hair, Skin & Nails",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 168,
      rating: 5,
      image: "images/f-grid-12.png",
      category: "Supplements, Beauty & Skin Health",
    },
    {
      id: "f13",
      name: "Vitamin C + D Effervescent Tablets",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 59,
      rating: 5,
      image: "images/f-grid-13.png",
      category: "Supplements, Immune Support",
    },
    {
      id: "f14",
      name: "Your Gummie – Iron",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 74,
      rating: 5,
      image: "images/f-grid-14.png",
      category: "Supplements, Blood Health",
    },
    {
      id: "f15",
      name: "Your Gummie – Elderberry",
      label: "Sale",
      price: "$16.00 – $35.00",
      reviews: 1,
      rating: 5,
      image: "images/f-grid-15.png",
      category: "Supplements, Immune Support",
    },
  ],

  bestSelling: [
    {
      id: "b1",
      name: "Codixvitamin D3 Oral Solution",
      label: "New",
      price: "$18.00 - $35.00",
      reviews: 85,
      rating: 5,
      image: "images/product-vitamin-cd.jpg",
      category: "Supplements",
    },
    {
      id: "b2",
      name: "YOUR GUMMIE Collagen Plus +",
      label: "Sale",
      price: "$16.00 - $25.00",
      reviews: 103,
      rating: 5,
      image: "images/product-gummie.jpg",
      category: "Supplements",
    },
    {
      id: "b3",
      name: "Boloss Liver Support Complex",
      label: "Sale",
      price: "$19.00 - $28.00",
      reviews: 78,
      rating: 5,
      image: "images/product-capsules.jpg",
      category: "Medicines",
    },
    {
      id: "b4",
      name: "Essence – Evening Primrose Oil",
      label: "New",
      price: "$16.00 - $22.00",
      reviews: 47,
      rating: 5,
      image: "images/product-purple.jpg",
      category: "Herbs",
    },
    {
      id: "b5",
      name: "Your Gummy – Milk Multi Gummies",
      label: "Sale",
      price: "$20.00 - $32.00",
      reviews: 168,
      rating: 5,
      image: "images/product-gummie.jpg",
      category: "Supplements",
    },
  ],

  categories: ["Supplements", "Medicines", "Herbs"],
};

const HERO_SLIDES = [
  {
    title: "YOUR GUMMIE",
    titleHighlight: "FOR MEN",
    subtitle: "Support Your Strength, Every Day",
    button: "Buy it now",
    bgImage: "images/hero-bg.png",
  },
  {
    title: "CODIX EVEROSE",
    titleHighlight: "DAILY CARE",
    subtitle: "Balanced Daily Vitamins Crafted For Modern Wellness",
    button: "Shop Everose",
    bgImage: "images/hero-bg.png",
  },
  {
    title: "FLEXICOD",
    titleHighlight: "JOINT SUPPORT",
    subtitle: "Advanced Mobility Support With Premium Botanical Extracts",
    button: "Shop Flexicod",
    bgImage: "images/hero-bg.png",
  },
];

const TESTIMONIALS = [
  {
    quote:
      "But I have been using for about 18 Mo contain a lot of researching relevant and effective for the body.",
    name: "Tina Lee",
    rating: 5,
  },
  {
    quote:
      "There was a small problem in the order, the service got this center under and I could live really good. The delivery was fast enough.",
    name: "Michael Shaw",
    rating: 5,
  },
  {
    quote:
      "Those selling this DO provide quality changes but only brand I use. I use changes to space of months by buying from them.",
    name: "Aisha Roberts",
    rating: 5,
  },
];

const BLOG_POSTS = [
  {
    title: "5 Natural Ways to Strengthen Your Immune System",
    description:
      "Discover simple lifestyle habits and key supplements that can naturally boost your immunity...",
    image: "images/blog-immune.jpg",
    tag: "Wellness Guide",
  },
  {
    title: "Skincare Advice for Sensitive Skin: Simple Tips for a Calmer Glow",
    description:
      "Learn how to care for sensitive skin with gentle routines and dermatologist recommended products.",
    image: "images/blog-immune.jpg",
    tag: "Beauty & Skin",
  },
  {
    title: "Do You Really Need Supplements? A Practical Guide to Boosting Health",
    description:
      "Find out when supplements are helpful and how to choose the right ones for your health needs.",
    image: "images/blog-immune.jpg",
    tag: "Health Guide",
  },
];

const TRUST_ITEMS = [
  { icon: "fa-money-bill-wave", label: "100% Money back", description: "Satisfaction guaranteed." },
  { icon: "fa-shipping-fast", label: "Non-contact shipping", description: "Safe delivery." },
  { icon: "fa-truck", label: "Free delivery over $200", description: "On higher orders." },
];

const SAMPLE_SEARCH_PRODUCTS = [
  "Codix Vitamin C+D",
  "Your Gummie Fish Oil",
  "ReliefMax Capsules",
  "Herbal Immune Support",
  "Daily Focus Gummies",
  "Relax Herbal Blend",
  "Joint Relief Boost",
  "Codix Everose",
  "Flexicod",
  "Codix Fatburner",
  "Daily Balance",
];
